package org.acme.domain.exception

class UsernameAlreadyExistsException: RuntimeException("Usuário já existe!")